using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.Localization;

namespace BOF.Campaign.Party
{
    public abstract class PartyComponent
    {
        public delegate void OnPartyComponentCreatedDelegate(MobileParty mobileParty);

        public MobileParty MobileParty { get; private set; }

        public PartyBase Party => this.MobileParty.Party;

        public abstract Hero PartyOwner { get; }

        public abstract TextObject Name { get; }

        public abstract Settlement HomeSettlement { get; }

        public virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
        {
        }

        public void SetMobilePartyInternal(MobileParty party) => this.MobileParty = party;

        public void Initialize(MobileParty party)
        {
            this.SetMobilePartyInternal(party);
            this.OnInitialize();
        }

        public void Finish() => this.OnFinalize();

        protected virtual void OnInitialize()
        {
        }

        protected virtual void OnFinalize()
        {
        }

        public virtual void ClearCachedName()
        {
        }
    }
}