using System.Collections.Generic;
using BOF.Campaign.Faction;

namespace BOF.Campaign.Party
{
    public abstract class WarPartyComponent : PartyComponent
    {
        public Clan Clan => this.Party.MobileParty.ActualClan;
        public override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects) => base.AutoGeneratedInstanceCollectObjects(collectedObjects);

        protected override void OnInitialize() => this.Clan.AddWarPartyInternal(this);

        protected override void OnFinalize() => this.Clan.RemoveWarPartyInternal(this);

        public void OnClanChange(Clan oldClan, Clan newClan)
        {
            oldClan.RemoveWarPartyInternal(this);
            newClan.AddWarPartyInternal(this);
        }
    }
}