using System.Collections.Generic;
using TaleWorlds.SaveSystem;

namespace BOF.Campaign
{
    public class MapTimeTracker
    {
        [SaveableField(0)]
        private long _numTicks;
        [SaveableField(1)]
        private long _deltaTimeInTicks;

        public static void AutoGeneratedStaticCollectObjectsMapTimeTracker(
            object o,
            List<object> collectedObjects)
        {
            ((MapTimeTracker) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
        }

        protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
        {
        }

        public static object AutoGeneratedGetMemberValue_numTicks(object o) => (object) ((MapTimeTracker) o)._numTicks;

        public static object AutoGeneratedGetMemberValue_deltaTimeInTicks(object o) => (object) ((MapTimeTracker) o)._deltaTimeInTicks;

        public long NumTicks => this._numTicks;

        public long DeltaTimeInTicks => this._deltaTimeInTicks;

        public MapTimeTracker(CampaignTime intialMapTime) => this._numTicks = intialMapTime.NumTicks;

        public MapTimeTracker() => this._numTicks = 0L;

        public CampaignTime Now => new CampaignTime(this._numTicks);

        public void Tick(float seconds)
        {
            this._deltaTimeInTicks = (long) ((double) seconds * 10000.0);
            this._numTicks += this._deltaTimeInTicks;
        }
    }

}