using System.Collections.Generic;

namespace BOF.CampaignSystem
{
    public class MapTimeTracker
    {
        // [SaveableField(0)]
        private long _numTicks;
        // [SaveableField(1)]
        private long _deltaTimeInTicks;


        protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
        {
        }

        public long NumTicks => this._numTicks;

        public long DeltaTimeInTicks => this._deltaTimeInTicks;

        public MapTimeTracker(CampaignTime intialMapTime) => this._numTicks = intialMapTime.NumTicks;

        public MapTimeTracker() => this._numTicks = 0L;

        public CampaignTime Now => new CampaignTime(this._numTicks);

        internal void Tick(float seconds)
        {
            this._deltaTimeInTicks = (long) ((double) seconds * 10000.0);
            this._numTicks += this._deltaTimeInTicks;
        }
    }
}