using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml;
using BOF.Campaign.Character;
using BOF.Campaign.Faction;
using BOF.Campaign.Map.Entity;
using BOF.Campaign.Utility;
using Helpers;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;
using TaleWorlds.SaveSystem.Load;

namespace BOF.Campaign.MapEntity
{
  public class Settlement : 
    MBObjectBase,
    ILocatable<Settlement>,
    IMapPoint,
    ITrackableCampaignObject,
    ITrackableBase,
    ISiegeEventSide,
    IMapEntity
  {
    
    public int NumberOfLordPartiesTargeting;
    
    public int NumberOfLordPartiesAt;
    
    public int CanBeClaimed;
    
    public float ClaimValue;
    
    public Hero ClaimedBy;
    
    public bool HasVisited;
    
    public bool IsQuestSettlement;
    
    private Dictionary<IFaction, float> _valueForFaction;
    
    public float LastVisitTimeOfOwner;
    
    private bool _isVisible;
    [CachedData]
    private int _locatorNodeIndex;
    
    private Settlement _nextLocatable;
    
    private float _prosperity;
    
    private float _readyMilitia;
    
    private List<float> _settlementWallSectionHitPointsRatioList = new List<float>();
    public MBReadOnlyList<float> SettlementWallSectionHitPointsRatioList;
    [CachedData]
    private List<MobileParty> _partiesCache;
    [CachedData]
    private List<Hero> _heroesWithoutPartyCache;
    [CachedData]
    private List<Hero> _notablesCache;
    private List<SettlementComponent> _settlementComponents;
    private Vec2 _gatePosition;
    private Vec2 _position;
    public CultureObject Culture;
    private TextObject _name;
    
    private List<Village> _boundVillages;
    
    private MobileParty _lastAttackerParty;
    
    public int PassedHoursAfterLastThreat;
    
    private List<SiegeEvent.SiegeEngineMissile> _siegeEngineMissiles;
    
    public Town Town;
    
    public Village Village;
    
    public Hideout Hideout;
    
    public bool SettlementTaken;
    
    public List<Settlement.SiegeLane> SiegeLanes = new List<Settlement.SiegeLane>();
    
    public Clan _ownerClanDepricated;
    [CachedData]
    public MilitiaPartyComponent MilitiaPartyComponent;
    
    public readonly ItemRoster Stash;

    public static void AutoGeneratedStaticCollectObjectsSettlement(
      object o,
      List<object> collectedObjects)
    {
      ((MBObjectBase) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
    }

    protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
    {
      base.AutoGeneratedInstanceCollectObjects(collectedObjects);
      collectedObjects.Add((object) this.ClaimedBy);
      collectedObjects.Add((object) this.Town);
      collectedObjects.Add((object) this.Village);
      collectedObjects.Add((object) this.Hideout);
      collectedObjects.Add((object) this.SiegeLanes);
      collectedObjects.Add((object) this._ownerClanDepricated);
      collectedObjects.Add((object) this.Stash);
      collectedObjects.Add((object) this._valueForFaction);
      collectedObjects.Add((object) this._nextLocatable);
      collectedObjects.Add((object) this._settlementWallSectionHitPointsRatioList);
      collectedObjects.Add((object) this._boundVillages);
      collectedObjects.Add((object) this._lastAttackerParty);
      collectedObjects.Add((object) this._siegeEngineMissiles);
      collectedObjects.Add((object) this.Party);
      collectedObjects.Add((object) this.SiegeEvent);
      collectedObjects.Add((object) this.SiegeEngines);
      collectedObjects.Add((object) this.SiegeStrategy);
      collectedObjects.Add((object) this.CommonAreas);
      collectedObjects.Add((object) this.LocationComplex);
      collectedObjects.Add((object) this._oldMilitaParty);
    }

    public static object AutoGeneratedGetMemberValueParty(object o) => (object) ((Settlement) o).Party;

    public static object AutoGeneratedGetMemberValueBribePaid(object o) => (object) ((Settlement) o).BribePaid;

    public static object AutoGeneratedGetMemberValueSiegeEvent(object o) => (object) ((Settlement) o).SiegeEvent;

    public static object AutoGeneratedGetMemberValueIsActive(object o) => (object) ((Settlement) o).IsActive;

    public static object AutoGeneratedGetMemberValueNumberOfEnemiesSpottedAround(object o) => (object) ((Settlement) o).NumberOfEnemiesSpottedAround;

    public static object AutoGeneratedGetMemberValueNumberOfAlliesSpottedAround(object o) => (object) ((Settlement) o).NumberOfAlliesSpottedAround;

    public static object AutoGeneratedGetMemberValueSettlementHitPoints(object o) => (object) ((Settlement) o).SettlementHitPoints;

    public static object AutoGeneratedGetMemberValueSiegeEngines(object o) => (object) ((Settlement) o).SiegeEngines;

    public static object AutoGeneratedGetMemberValueNumberOfTroopsKilledOnSide(object o) => (object) ((Settlement) o).NumberOfTroopsKilledOnSide;

    public static object AutoGeneratedGetMemberValueSiegeStrategy(object o) => (object) ((Settlement) o).SiegeStrategy;

    public static object AutoGeneratedGetMemberValueCommonAreas(object o) => (object) ((Settlement) o).CommonAreas;

    public static object AutoGeneratedGetMemberValueLocationComplex(object o) => (object) ((Settlement) o).LocationComplex;

    public static object AutoGeneratedGetMemberValueCurrentSiegeState(object o) => (object) ((Settlement) o).CurrentSiegeState;

    public static object AutoGeneratedGetMemberValue_oldMilitaParty(object o) => (object) ((Settlement) o)._oldMilitaParty;

    public static object AutoGeneratedGetMemberValueNumberOfLordPartiesTargeting(object o) => (object) ((Settlement) o).NumberOfLordPartiesTargeting;

    public static object AutoGeneratedGetMemberValueNumberOfLordPartiesAt(object o) => (object) ((Settlement) o).NumberOfLordPartiesAt;

    public static object AutoGeneratedGetMemberValueCanBeClaimed(object o) => (object) ((Settlement) o).CanBeClaimed;

    public static object AutoGeneratedGetMemberValueClaimValue(object o) => (object) ((Settlement) o).ClaimValue;

    public static object AutoGeneratedGetMemberValueClaimedBy(object o) => (object) ((Settlement) o).ClaimedBy;

    public static object AutoGeneratedGetMemberValueHasVisited(object o) => (object) ((Settlement) o).HasVisited;

    public static object AutoGeneratedGetMemberValueIsQuestSettlement(object o) => (object) ((Settlement) o).IsQuestSettlement;

    public static object AutoGeneratedGetMemberValueLastVisitTimeOfOwner(object o) => (object) ((Settlement) o).LastVisitTimeOfOwner;

    public static object AutoGeneratedGetMemberValuePassedHoursAfterLastThreat(object o) => (object) ((Settlement) o).PassedHoursAfterLastThreat;

    public static object AutoGeneratedGetMemberValueTown(object o) => (object) ((Settlement) o).Town;

    public static object AutoGeneratedGetMemberValueVillage(object o) => (object) ((Settlement) o).Village;

    public static object AutoGeneratedGetMemberValueHideout(object o) => (object) ((Settlement) o).Hideout;

    public static object AutoGeneratedGetMemberValueSettlementTaken(object o) => (object) ((Settlement) o).SettlementTaken;

    public static object AutoGeneratedGetMemberValueSiegeLanes(object o) => (object) ((Settlement) o).SiegeLanes;

    public static object AutoGeneratedGetMemberValue_ownerClanDepricated(object o) => (object) ((Settlement) o)._ownerClanDepricated;

    public static object AutoGeneratedGetMemberValueStash(object o) => (object) ((Settlement) o).Stash;

    public static object AutoGeneratedGetMemberValue_valueForFaction(object o) => (object) ((Settlement) o)._valueForFaction;

    public static object AutoGeneratedGetMemberValue_isVisible(object o) => (object) ((Settlement) o)._isVisible;

    public static object AutoGeneratedGetMemberValue_nextLocatable(object o) => (object) ((Settlement) o)._nextLocatable;

    public static object AutoGeneratedGetMemberValue_prosperity(object o) => (object) ((Settlement) o)._prosperity;

    public static object AutoGeneratedGetMemberValue_readyMilitia(object o) => (object) ((Settlement) o)._readyMilitia;

    public static object AutoGeneratedGetMemberValue_settlementWallSectionHitPointsRatioList(
      object o)
    {
      return (object) ((Settlement) o)._settlementWallSectionHitPointsRatioList;
    }

    public static object AutoGeneratedGetMemberValue_boundVillages(object o) => (object) ((Settlement) o)._boundVillages;

    public static object AutoGeneratedGetMemberValue_lastAttackerParty(object o) => (object) ((Settlement) o)._lastAttackerParty;

    public static object AutoGeneratedGetMemberValue_siegeEngineMissiles(object o) => (object) ((Settlement) o)._siegeEngineMissiles;

    
    public PartyBase Party { get; private set; }

    
    public int BribePaid { get; set; }

    
    public SiegeEvent SiegeEvent { get; set; }

    
    public bool IsActive { get; set; }

    public Hero Owner => this.OwnerClan.Leader;

    public bool IsVisible
    {
      get => this._isVisible;
      set
      {
        if (this._isVisible == value)
          return;
        this._isVisible = value;
        this.Party.OnVisibilityChanged(value);
      }
    }

    public bool IsInspected { get; set; }

    public int WallSectionCount { get; private set; }

    int ILocatable<Settlement>.LocatorNodeIndex
    {
      get => this._locatorNodeIndex;
      set => this._locatorNodeIndex = value;
    }

    
    public float NumberOfEnemiesSpottedAround { get; set; }

    
    public float NumberOfAlliesSpottedAround { get; set; }

    Settlement ILocatable<Settlement>.NextLocatable
    {
      get => this._nextLocatable;
      set => this._nextLocatable = value;
    }

    public float Prosperity
    {
      get => this._prosperity;
      set
      {
        this._prosperity = value;
        if ((double) this._prosperity >= 0.0)
          return;
        this._prosperity = 0.0f;
      }
    }

    public Vec2 GetPosition2D => this.Position2D;

    public float Militia
    {
      get => (this.MilitiaPartyComponent == null || !this.MilitiaPartyComponent.MobileParty.IsActive ? 0.0f : (float) this.MilitiaPartyComponent.MobileParty.Party.NumberOfAllMembers) + this._readyMilitia;
      set
      {
        int num = this.MilitiaPartyComponent == null || !this.MilitiaPartyComponent.MobileParty.IsActive ? 0 : this.MilitiaPartyComponent.MobileParty.Party.NumberOfAllMembers;
        this._readyMilitia = value - (float) num;
        if ((double) this._readyMilitia < (double) -num)
          this._readyMilitia = (float) -num;
        if ((double) this._readyMilitia >= -1.0 && (double) this._readyMilitia <= 1.0)
          return;
        if (this.MilitiaPartyComponent != null)
          this.TransferReadyMilitiasToMilitiaParty();
        else
          this.SpawnMilitiaParty();
      }
    }

    public float SettlementTotalWallHitPoints
    {
      get
      {
        float num = 0.0f;
        foreach (float sectionHitPointsRatio in this._settlementWallSectionHitPointsRatioList)
          num += sectionHitPointsRatio;
        return num * this.MaxHitPointsOfOneWallSection;
      }
    }

    public float MaxHitPointsOfOneWallSection => this.WallSectionCount == 0 ? 0.0f : this.MaxWallHitPoints / (float) this.WallSectionCount;

    public void SetWallSectionHitPointsRatioAtIndex(int index, float hitPointsRatio) => this._settlementWallSectionHitPointsRatioList[index] = MBMath.ClampFloat(hitPointsRatio, 0.0f, 1f);

    
    public float SettlementHitPoints { get; public set; }

    public float MaxWallHitPoints => Campaign.Current.Models.WallHitPointCalculationModel.CalculateMaximumWallHitPoint(this.Town);

    public MBReadOnlyList<MobileParty> Parties { get; private set; }

    public MBReadOnlyList<Hero> HeroesWithoutParty { get; private set; }

    public MBReadOnlyList<Hero> Notables { get; private set; }

    public IEnumerable<SettlementComponent> SettlementComponents => this._settlementComponents.AsEnumerable<SettlementComponent>();

    public Vec2 GatePosition
    {
      get => this._gatePosition;
      private set
      {
        this._gatePosition = value;
        Campaign current = Campaign.Current;
        if (current.MapSceneWrapper == null)
          return;
        this.CurrentNavigationFace = current.MapSceneWrapper.GetFaceIndex(this._gatePosition);
      }
    }

    public Vec2 Position2D
    {
      get => this._position;
      private set
      {
        this._position = value;
        Campaign.Current.SettlementLocator.UpdateParty(this);
      }
    }

    public PathFaceRecord CurrentNavigationFace { get; private set; }

    public Vec3 GetLogicalPosition()
    {
      float height = 0.0f;
      Campaign.Current.MapSceneWrapper.GetHeightAtPoint(this.Position2D, ref height);
      return new Vec3(this.Position2D.x, this.Position2D.y, height);
    }

    public IFaction MapFaction => this.Town?.MapFaction ?? this.Village?.Bound.MapFaction ?? this.Hideout?.MapFaction ?? (IFaction) null;

    public TextObject Name
    {
      get => this._name;
      set => this.SetName(value);
    }

    public TextObject EncyclopediaText { get; private set; }

    public string EncyclopediaLink => Campaign.Current.EncyclopediaManager.GetIdentifier(typeof (Settlement)) + "-" + this.StringId ?? "";

    public TextObject EncyclopediaLinkWithName => HyperlinkTexts.GetSettlementHyperlinkText(this.EncyclopediaLink, this.Name);

    public ItemRoster ItemRoster => this.Party.ItemRoster;

    public MBReadOnlyList<Village> BoundVillages { get; private set; }

    public DeterministicRandom Random => this.Party.Random;

    public MobileParty LastAttackerParty
    {
      get => this._lastAttackerParty;
      set
      {
        if (this._lastAttackerParty != value)
        {
          this._lastAttackerParty = value;
          if (value != null && (this.IsFortification || this.IsVillage))
          {
            foreach (Settlement settlement in Settlement.All)
            {
              if ((settlement.IsFortification || settlement.IsVillage) && settlement.LastAttackerParty == value)
                settlement.LastAttackerParty = (MobileParty) null;
            }
          }
          this._lastAttackerParty = value;
        }
        if (value != null)
          this.PassedHoursAfterLastThreat = 24;
        else
          this.PassedHoursAfterLastThreat = 0;
      }
    }

    
    public SiegeEvent.SiegeEnginesContainer SiegeEngines { get; private set; }

    public MBReadOnlyList<SiegeEvent.SiegeEngineMissile> SiegeEngineMissiles { get; private set; }

    public BattleSideEnum BattleSide => BattleSideEnum.Defender;

    
    public int NumberOfTroopsKilledOnSide { get; private set; }

    
    public SiegeStrategy SiegeStrategy { get; private set; }

    public IEnumerable<PartyBase> SiegeParties
    {
      get
      {
        yield return this.Party;
        foreach (MobileParty party in this.Parties)
        {
          if (party.MapFaction.IsAtWarWith(this.SiegeEvent.BesiegerCamp.BesiegerParty.MapFaction) && !party.IsVillager && !party.IsCaravan && !this.InRebelliousState || this.InRebelliousState && !party.IsMilitia)
            yield return party.Party;
        }
      }
    }

    public void AddBoundVillagepublic(Village village) => this._boundVillages.Add(village);

    public void RemoveBoundVillagepublic(Village village) => this._boundVillages.Remove(village);

    
    public List<CommonArea> CommonAreas { get; private set; }

    private void SetName(TextObject name)
    {
      this._name = name;
      this.SetNameAttributes();
    }

    private void SetNameAttributes()
    {
      this._name.SetTextVariable("IS_SETTLEMENT", 1);
      this._name.SetTextVariable("IS_CASTLE", this.IsCastle ? 1 : 0);
      this._name.SetTextVariable("IS_TOWN", this.IsTown ? 1 : 0);
      this._name.SetTextVariable("IS_HIDEOUT", this.IsHideout ? 1 : 0);
    }

    private void InitSettlement()
    {
      this._settlementComponents = new List<SettlementComponent>();
      this._partiesCache = new List<MobileParty>();
      this.Parties = new MBReadOnlyList<MobileParty>(this._partiesCache);
      this._heroesWithoutPartyCache = new List<Hero>();
      this.HeroesWithoutParty = new MBReadOnlyList<Hero>(this._heroesWithoutPartyCache);
      this._notablesCache = new List<Hero>();
      this.Notables = new MBReadOnlyList<Hero>(this._notablesCache);
      this._boundVillages = new List<Village>();
      this.BoundVillages = this._boundVillages.GetReadOnlyList<Village>();
      this.CurrentManagementAIState = Settlement.ManagementAIState.ConstructBuilding;
      this.SettlementHitPoints = 1f;
      this.CurrentSiegeState = Settlement.SiegeState.OnTheWalls;
      this._valueForFaction = new Dictionary<IFaction, float>();
      this.LastVisitTimeOfOwner = Campaign.CurrentTime;
      this.SettlementWallSectionHitPointsRatioList = new MBReadOnlyList<float>(this._settlementWallSectionHitPointsRatioList);
    }

    public bool IsTown => this.Town != null && this.Town.IsTown;

    public bool IsCastle => this.Town != null && this.Town.IsCastle;

    public bool IsFortification => this.IsTown || this.IsCastle;

    public bool IsVillage => this.Village != null;

    public bool IsHideout => this.Hideout != null;

    public bool HasRecruits => this.GetNumberOfAvailableRecruits() == 1;

    public bool HasMultipleRecruits => this.GetNumberOfAvailableRecruits() > 1;

    public bool HasFestival => false;

    public bool IsStarving => this.Town != null && (double) this.Town.FoodStocks <= 0.0;

    public bool IsRaided => this.IsVillage && this.Village.VillageState == this.Village.VillageStates.Looted;

    public bool IsBooming
    {
      get
      {
        float num = 50f;
        if (this.IsTown || this.IsCastle)
          num = this.Town.Loyalty;
        else if (this.IsVillage)
          num = this.Village.Bound.Town.Loyalty;
        return (double) num > 80.0;
      }
    }

    public bool InRebelliousState => (this.IsTown || this.IsCastle) && this.Town.InRebelliousState;

    public bool IsUnderRaid => this.Party.MapEvent != null && this.Party.MapEvent.IsRaid;

    public bool IsUnderSiege => this.SiegeEvent != null && this.SiegeEvent.BesiegerCamp.SiegeParties.Any<PartyBase>();

    public int GetNumberOfAvailableRecruits()
    {
      int num = 0;
      foreach (Hero notable in this.Notables)
      {
        for (int index = 0; index < 6; ++index)
        {
          if (HeroHelper.HeroCanRecruitFromHero(Hero.MainHero, notable, index))
            ++num;
        }
      }
      return num;
    }

    public bool IsUnderRebellionAttack()
    {
      if (this.Party.MapEvent != null && this.Party.MapEvent.IsSiegeAssault)
      {
        Hero owner = this.Party.MapEvent.AttackerSide.LeaderParty.MobileParty.Party.Owner;
        if (owner != null && owner.Clan.IsRebelClan)
          return true;
      }
      return false;
    }

    public T AddComponent<T>() where T : SettlementComponent
    {
      T obj = default (T);
      if (typeof (T).IsSubclassOf(typeof (SettlementComponent)))
        obj = Activator.CreateInstance(typeof (T)) as T;
      if ((object) obj != null)
      {
        obj.Owner = this.Party;
        this._settlementComponents.Add((SettlementComponent) obj);
        obj.OnStart();
      }
      return obj;
    }

    public SettlementComponent GetComponent(Type type)
    {
      for (int index = 0; index < this._settlementComponents.Count; ++index)
      {
        if (type.IsInstanceOfType((object) this._settlementComponents[index]))
          return this._settlementComponents[index];
      }
      return (SettlementComponent) null;
    }

    public T GetComponent<T>() where T : SettlementComponent
    {
      for (int index = 0; index < this._settlementComponents.Count; ++index)
      {
        if (this._settlementComponents[index] is T)
          return (T) this._settlementComponents[index];
      }
      return default (T);
    }

    public Settlement()
      : this(new TextObject("{=!}unnamed"), (LocationComplex) null, (PartyTemplateObject) null)
    {
    }

    public Settlement(TextObject name, LocationComplex locationComplex, PartyTemplateObject pt)
    {
      this._name = name;
      this._isVisible = true;
      this.IsActive = true;
      this.Party = new PartyBase(this);
      this.InitSettlement();
      this._position = Vec2.Zero;
      this.LocationComplex = locationComplex;
      this.CommonAreas = new List<CommonArea>();
      this.HasVisited = false;
      this.Stash = new ItemRoster();
    }

    private Settlement.ManagementAIState CurrentManagementAIState { get; set; }

    public void Think()
    {
      if (this.CurrentManagementAIState != Settlement.ManagementAIState.GiveQuest)
        return;
      PartyBase partyBase = (PartyBase) null;
      float maximumDistance = 1E+07f;
      foreach (MobileParty mobileParty in Campaign.Current.MobileParties)
      {
        float distance;
        if (mobileParty.MapFaction.IsBanditFaction && Campaign.Current.Models.MapDistanceModel.GetDistance(mobileParty, this, maximumDistance, out distance))
        {
          maximumDistance = distance;
          partyBase = mobileParty.Party;
        }
      }
      if (partyBase == null)
        throw new MBNullParameterException("[DEBUG]targetParty");
    }

    
    public LocationComplex LocationComplex { get; private set; }

    public static Settlement CurrentSettlement
    {
      get
      {
        if (PlayerCaptivity.CaptorParty != null && PlayerCaptivity.CaptorParty.IsSettlement)
          return PlayerCaptivity.CaptorParty.Settlement;
        if (PlayerEncounter.EncounterSettlement != null)
          return PlayerEncounter.EncounterSettlement;
        return MobileParty.MainParty.CurrentSettlement != null ? MobileParty.MainParty.CurrentSettlement : (Settlement) null;
      }
    }

    public float GetValue(bool countAlsoBoundedSettlements = true)
    {
      float num = 0.0f;
      if (this.IsVillage)
        num = (float) ((100000.0 + (double) this.Village.Hearth * 250.0) * (this.Village.VillageState == this.Village.VillageStates.Looted ? 0.800000011920929 : (this.Village.VillageState == this.Village.VillageStates.BeingRaided ? 0.850000023841858 : 0.800000011920929 + (0.666999995708466 + 0.333000004291534 * (double) this.Village.Settlement.SettlementHitPoints) * 0.200000002980232)));
      else if (this.IsCastle)
        num = (float) (250000.0 + (double) this.Prosperity * 1000.0);
      else if (this.IsTown)
        num = (float) (750000.0 + (double) this.Prosperity * 1000.0);
      if (countAlsoBoundedSettlements)
      {
        foreach (Village boundVillage in this.BoundVillages)
          num += boundVillage.Settlement.GetValue(false);
      }
      return num;
    }

    public override TextObject GetName() => this.Name;

    public float GetSettlementValueForFaction(IFaction faction)
    {
      float num;
      return this._valueForFaction.TryGetValue(faction, out num) ? num : 0.0f;
    }

    public void CalculateSettlementValueForFactions()
    {
      if (this.IsFortification)
      {
        foreach (Kingdom kingdom in Kingdom.All)
        {
          float valueForFaction = Campaign.Current.Models.SettlementValueModel.CalculateValueForFaction(this, (IFaction) kingdom);
          if (!this._valueForFaction.ContainsKey((IFaction) kingdom))
            this._valueForFaction.Add((IFaction) kingdom, valueForFaction);
          else
            this._valueForFaction[(IFaction) kingdom] = valueForFaction;
        }
        foreach (Clan clan in Clan.All)
        {
          float valueForFaction = Campaign.Current.Models.SettlementValueModel.CalculateValueForFaction(this, (IFaction) clan);
          if (!this._valueForFaction.ContainsKey((IFaction) clan))
            this._valueForFaction.Add((IFaction) clan, valueForFaction);
          else
            this._valueForFaction[(IFaction) clan] = valueForFaction;
        }
      }
      else
      {
        if (!this.IsVillage)
          return;
        this._valueForFaction.Clear();
        this._valueForFaction.Add(this.MapFaction, Campaign.Current.Models.SettlementValueModel.CalculateValueForFaction(this, this.MapFaction));
      }
    }

    public override string ToString() => this.Name.ToString();

    public void OnRelatedPartyRemoved(MobileParty mobileParty)
    {
      foreach (SettlementComponent settlementComponent in this.SettlementComponents)
        settlementComponent.OnRelatedPartyRemoved(mobileParty);
    }

    public void AddMobileParty(MobileParty mobileParty)
    {
      if (this._partiesCache.Contains(mobileParty))
        return;
      this._partiesCache.Add(mobileParty);
    }

    public void RemoveMobileParty(MobileParty mobileParty)
    {
      if (!this._partiesCache.Contains(mobileParty))
        return;
      this._partiesCache.Remove(mobileParty);
    }

    public void AddHeroWithoutParty(Hero individual)
    {
      if (this._heroesWithoutPartyCache.Contains(individual))
        return;
      this._heroesWithoutPartyCache.Add(individual);
      this.CollectNotablesToCache();
    }

    public void RemoveHeroWithoutParty(Hero individual)
    {
      if (!this._heroesWithoutPartyCache.Contains(individual))
        return;
      this._heroesWithoutPartyCache.Remove(individual);
      this.CollectNotablesToCache();
    }

    private void CollectNotablesToCache()
    {
      this._notablesCache.Clear();
      foreach (Hero hero in this.HeroesWithoutParty)
      {
        if (hero.IsNotable)
          this._notablesCache.Add(hero);
      }
    }

    public override void Deserialize(MBObjectManager objectManager, XmlNode node)
    {
      bool isInitialized = this.IsInitialized;
      base.Deserialize(objectManager, node);
      this.Name = new TextObject(node.Attributes["name"].Value);
      this.Position2D = new Vec2((float) Convert.ToDouble(node.Attributes["posX"].Value), (float) Convert.ToDouble(node.Attributes["posY"].Value));
      this.GatePosition = this.Position2D;
      if (node.Attributes["gate_posX"] != null)
        this.GatePosition = new Vec2((float) Convert.ToDouble(node.Attributes["gate_posX"].Value), (float) Convert.ToDouble(node.Attributes["gate_posY"].Value));
      if (!isInitialized && node.Attributes["prosperity"] != null)
        this.Prosperity = (float) Convert.ToDouble(node.Attributes["prosperity"].Value);
      this.Culture = objectManager.ReadObjectReferenceFromXml<CultureObject>("culture", node);
      this.EncyclopediaText = node.Attributes["text"] != null ? new TextObject(node.Attributes["text"].Value) : TextObject.Empty;
      if (Campaign.Current != null && Campaign.Current.MapSceneWrapper != null && !Campaign.Current.MapSceneWrapper.GetFaceIndex(this.Position2D).IsValid())
        Debug.Print("Center position of settlement(" + (object) this.GetName() + ") is invalid");
      foreach (XmlNode childNode1 in node.ChildNodes)
      {
        if (childNode1.Name == "Components")
        {
          foreach (XmlNode childNode2 in childNode1.ChildNodes)
          {
            SettlementComponent objectFromXmlNode = (SettlementComponent) objectManager.CreateObjectFromXmlNode(childNode2);
            objectFromXmlNode.Owner = this.Party;
            this._settlementComponents.Add(objectFromXmlNode);
          }
        }
        if (childNode1.Name == "Locations")
        {
          LocationComplexTemplate complexTemplate = (LocationComplexTemplate) objectManager.ReadObjectReferenceFromXml("complex_template", typeof (LocationComplexTemplate), childNode1);
          if (!isInitialized)
            this.LocationComplex = new LocationComplex(complexTemplate);
          else
            this.LocationComplex.Initialize(complexTemplate);
          foreach (XmlNode childNode3 in childNode1.ChildNodes)
          {
            if (childNode3.Name == "Location")
            {
              Location locationWithId = this.LocationComplex.GetLocationWithId(childNode3.Attributes["id"].Value);
              if (childNode3.Attributes["max_prosperity"] != null)
                locationWithId.ProsperityMax = int.Parse(childNode3.Attributes["max_prosperity"].Value);
              bool flag = false;
              for (int upgradeLevel = 0; upgradeLevel < 4; ++upgradeLevel)
              {
                string name = "scene_name" + (upgradeLevel > 0 ? "_" + (object) upgradeLevel : "");
                string sceneName = childNode3.Attributes[name] != null ? childNode3.Attributes[name].Value : "";
                flag = flag || !string.IsNullOrEmpty(sceneName);
                locationWithId.SetSceneName(upgradeLevel, sceneName);
              }
            }
          }
        }
        if (childNode1.Name == "CommonAreas")
        {
          int index = 0;
          foreach (XmlNode childNode4 in childNode1.ChildNodes)
          {
            if (childNode4.Name == "Area")
            {
              CommonArea.CommonAreaType result;
              Enum.TryParse<CommonArea.CommonAreaType>(childNode4.Attributes["type"].Value, true, out result);
              string str = childNode4.Attributes["name"].Value;
              string tag = "common_area_" + (object) (index + 1);
              if (!isInitialized)
                this.CommonAreas.Add(new CommonArea(this, tag, result, new TextObject(str)));
              else
                this.CommonAreas[index].Initialize(this, tag, result, new TextObject(str));
              ++index;
            }
          }
          foreach (CommonArea commonArea1 in this.CommonAreas)
          {
            foreach (CommonArea commonArea2 in this.CommonAreas)
              ;
          }
        }
        if (childNode1.Name == "ExcludedSiegeEquipments")
        {
          this.SiegeLanes = new List<Settlement.SiegeLane>(childNode1.ChildNodes.Count);
          foreach (XmlNode childNode5 in childNode1.ChildNodes)
          {
            Settlement.SiegeLaneEnum result1;
            Enum.TryParse<Settlement.SiegeLaneEnum>(childNode5.Attributes["id"].Value, true, out result1);
            bool result2;
            bool.TryParse(childNode5.Attributes["isGate"].Value, out result2);
            bool result3;
            bool.TryParse(childNode5.Attributes["isSiegeMachineApplicable"].Value, out result3);
            this.SiegeLanes.Add(new Settlement.SiegeLane(result1, result2, result3));
          }
        }
      }
      this.GetComponent<SettlementComponent>();
      foreach (SettlementComponent settlementComponent in this.SettlementComponents)
        settlementComponent.OnStart();
      if (!isInitialized)
      {
        Clan clan = objectManager.ReadObjectReferenceFromXml<Clan>("owner", node);
        if (clan != null && this.Town != null)
          this.Town.OwnerClan = clan;
      }
      this.SetNameAttributes();
    }

    public void OnFinishLoadState()
    {
      if (this.IsUnderSiege)
      {
        float height = 0.0f;
        Campaign.Current.MapSceneWrapper.GetHeightAtPoint(this.GatePosition, ref height);
        this.Party.Visuals.OnBesieged(new Vec3(this.GatePosition.x, this.GatePosition.y, height));
      }
      this.WallSectionCount = !this.IsFortification ? 0 : this.Party.Visuals.GetBreacableWallFrameCount();
      this.GetComponent(typeof (SettlementComponent))?.OnFinishLoadState();
      if (!(MBSaveLoad.LastLoadedGameVersion <= ApplicationVersion.FromString("e1.6.4.286844", ApplicationVersionGameType.Singleplayer)) || this.OwnerClan == null || !this.OwnerClan.IsEliminated)
        return;
      Clan clan = FactionHelper.ChooseHeirClanForFiefs(this.OwnerClan);
      foreach (Settlement settlement in this.OwnerClan.Settlements.ToList<Settlement>())
      {
        if (settlement.IsTown || settlement.IsCastle)
        {
          Hero elementWithPredicate = clan.Lords.GetRandomElementWithPredicate<Hero>((Func<Hero, bool>) (x => !x.IsChild));
          ChangeOwnerOfSettlementAction.ApplyByDestroyClan(settlement, elementWithPredicate);
        }
      }
    }

    public void OnGameInitialized() => this.CurrentNavigationFace = Campaign.Current.MapSceneWrapper.GetFaceIndex(this.GatePosition);

    public void OnGameCreated()
    {
      this.GetComponent<SettlementComponent>().OnInit();
      this.CreateFigure();
      this.Party.Visuals.RefreshLevelMask(this.Party);
      this.WallSectionCount = !this.IsFortification ? 0 : this.Party.Visuals.GetBreacableWallFrameCount();
      for (int index = 0; index < this.WallSectionCount; ++index)
        this._settlementWallSectionHitPointsRatioList.Add(1f);
    }

    public void OnSessionStart() => this.Party?.Visuals?.SetMapIconAsDirty();

    [LoadInitializationCallback]
    private void OnLoad(MetaData metaData, ObjectLoadData objectLoadData)
    {
      this._settlementComponents = new List<SettlementComponent>();
      this.SettlementWallSectionHitPointsRatioList = new MBReadOnlyList<float>(this._settlementWallSectionHitPointsRatioList);
      this.BoundVillages = this._boundVillages.GetReadOnlyList<Village>();
      List<SiegeEvent.SiegeEngineMissile> siegeEngineMissiles = this._siegeEngineMissiles;
      this.SiegeEngineMissiles = siegeEngineMissiles != null ? siegeEngineMissiles.GetReadOnlyList<SiegeEvent.SiegeEngineMissile>() : (MBReadOnlyList<SiegeEvent.SiegeEngineMissile>) null;
      ((ILocatable<Settlement>) this).LocatorNodeIndex = 0;
      this._partiesCache = new List<MobileParty>();
      this.Parties = new MBReadOnlyList<MobileParty>(this._partiesCache);
      this._heroesWithoutPartyCache = new List<Hero>();
      this.HeroesWithoutParty = new MBReadOnlyList<Hero>(this._heroesWithoutPartyCache);
      this._notablesCache = new List<Hero>();
    }

    public static Settlement Find(string idString) => MBObjectManager.Instance.GetObject<Settlement>(idString);

    public static Settlement FindFirst(Func<Settlement, bool> predicate) => Settlement.All.FirstOrDefault<Settlement>((Func<Settlement, bool>) (x => predicate(x)));

    public static IEnumerable<Settlement> FindAll(
      Func<Settlement, bool> predicate)
    {
      return Settlement.All.Where<Settlement>((Func<Settlement, bool>) (x => predicate(x)));
    }

    public static MBReadOnlyList<Settlement> All => Campaign.Current.Settlements;

    public static Settlement GetFirst => Settlement.All.FirstOrDefault<Settlement>();

    public static IEnumerable<Settlement> FindSettlementsAroundPosition(
      Vec2 position,
      float radius,
      Func<Settlement, bool> condition = null)
    {
      return condition != null ? Campaign.Current.SettlementLocator.FindPartiesAroundPosition(position, radius, condition) : Campaign.Current.SettlementLocator.FindPartiesAroundPosition(position, radius);
    }

    public void OnPlayerEncounterFinish()
    {
      if (this.LocationComplex == null)
        return;
      this.LocationComplex.ClearTempCharacters();
    }

    TextObject ITrackableBase.GetName() => this.Name;

    public Vec3 GetPosition() => this.GetLogicalPosition();

    public float GetTrackDistanceToMainAgent() => this.GetPosition().Distance(Hero.MainHero.GetPosition());

    public bool CheckTracked(BasicCharacterObject basicCharacter) => this.Notables.Any<Hero>((Func<Hero, bool>) (t => t.CharacterObject == basicCharacter)) || this.Party.PrisonRoster.GetTroopRoster().Any<TroopRosterElement>((Func<TroopRosterElement, bool>) (t => t.Character == basicCharacter)) || this.Parties.Any<MobileParty>((Func<MobileParty, bool>) (p => p.CheckTracked(basicCharacter)));

    private void CreateFigure() => this.Party.Visuals.OnStartup(this.Party);

    
    public Settlement.SiegeState CurrentSiegeState { get; private set; }

    public Clan OwnerClan
    {
      get
      {
        if (this.Village != null)
          return this.Village.Bound.OwnerClan;
        if (this.Town != null)
          return this.Town.OwnerClan;
        return this.IsHideout ? this.Hideout.MapFaction as Clan : (Clan) null;
      }
    }

    public bool IsAlerted => (double) this.NumberOfEnemiesSpottedAround >= 1.0;

    public void SetNextSiegeState()
    {
      if (this.CurrentSiegeState == Settlement.SiegeState.InTheLordsHall)
        return;
      ++this.CurrentSiegeState;
    }

    public void ResetSiegeState() => this.CurrentSiegeState = Settlement.SiegeState.OnTheWalls;

    public void AddGarrisonParty(bool addInitialGarrison = false) => GarrisonPartyComponent.CreateGarrisonParty("garrison_party_" + this.StringId + "_" + this.OwnerClan.StringId + "_1", this, addInitialGarrison);

    protected override void AfterLoad()
    {
      if (this.SiegeEvent != null && this.SiegeEvent.BesiegerCamp.BesiegerParty == null)
        this.SiegeEvent = (SiegeEvent) null;
      this._notablesCache = new List<Hero>();
      this.Notables = new MBReadOnlyList<Hero>(this._notablesCache);
      this.CollectNotablesToCache();
      this.Party.AfterLoad();
      if (this._oldMilitaParty != null)
        this.Militia = (float) this._oldMilitaParty.MemberRoster.TotalHealthyCount + this._readyMilitia;
      this.Party.UpdateVisibilityAndInspected();
    }

    
    public MobileParty _oldMilitaParty { get; set; }

    private void SpawnMilitiaParty()
    {
      this.MilitiaPartyComponent.CreateMilitiaParty("militias_of_" + this.StringId + "_aaa1", this);
      this.TransferReadyMilitiasToMilitiaParty();
    }

    private void TransferReadyMilitiasToMilitiaParty()
    {
      if ((double) this._readyMilitia >= 1.0)
      {
        int militiaToAdd = MathF.Floor(this._readyMilitia);
        this._readyMilitia -= (float) militiaToAdd;
        this.AddMilitiasToParty(this.MilitiaPartyComponent.MobileParty, militiaToAdd);
      }
      else
      {
        if ((int) this._readyMilitia >= -1)
          return;
        int num = MathF.Ceiling(this._readyMilitia);
        this._readyMilitia -= (float) num;
        Settlement.RemoveMilitiasFromParty(this.MilitiaPartyComponent.MobileParty, -num);
      }
    }

    private void AddMilitiasToParty(MobileParty militaParty, int militiaToAdd)
    {
      float meleeTroopRate;
      Campaign.Current.Models.SettlementMilitiaModel.CalculateMilitiaSpawnRate(this, out meleeTroopRate, out float _);
      this.AddTroopToMilitiaParty(militaParty, this.Culture.MeleeMilitiaTroop, this.Culture.MeleeEliteMilitiaTroop, meleeTroopRate, ref militiaToAdd);
      this.AddTroopToMilitiaParty(militaParty, this.Culture.RangedMilitiaTroop, this.Culture.RangedEliteMilitiaTroop, 1f, ref militiaToAdd);
    }

    private void AddTroopToMilitiaParty(
      MobileParty militaParty,
      CharacterObject militiaTroop,
      CharacterObject eliteMilitiaTroop,
      float troopRatio,
      ref int numberToAddRemaining)
    {
      if (numberToAddRemaining <= 0)
        return;
      int num = MBRandom.RoundRandomized(troopRatio * (float) numberToAddRemaining);
      float militiaSpawnChance = Campaign.Current.Models.SettlementMilitiaModel.CalculateEliteMilitiaSpawnChance(this);
      for (int index = 0; index < num; ++index)
      {
        if ((double) MBRandom.RandomFloat < (double) militiaSpawnChance)
          militaParty.MemberRoster.AddToCounts(eliteMilitiaTroop, 1);
        else
          militaParty.MemberRoster.AddToCounts(militiaTroop, 1);
      }
      numberToAddRemaining -= num;
    }

    private static void RemoveMilitiasFromParty(MobileParty militaParty, int numberToRemove)
    {
      if (militaParty.MemberRoster.TotalManCount <= numberToRemove)
      {
        militaParty.MemberRoster.Clear();
      }
      else
      {
        float num1 = (float) numberToRemove / (float) militaParty.MemberRoster.TotalManCount;
        int num2 = numberToRemove;
        for (int index = 0; index < militaParty.MemberRoster.Count; ++index)
        {
          int num3 = MBRandom.RoundRandomized((float) militaParty.MemberRoster.GetElementNumber(index) * num1);
          if (num3 > num2)
            num3 = num2;
          militaParty.MemberRoster.AddToCountsAtIndex(index, -num3, removeDepleted: false);
          num2 -= num3;
          if (num2 <= 0)
            break;
        }
        militaParty.MemberRoster.RemoveZeroCounts();
      }
    }

    public void SetSiegeStrategy(SiegeStrategy strategy) => this.SiegeStrategy = strategy;

    public void InitializeSiegeEventSide()
    {
      this.SiegeStrategy = DefaultSiegeStrategies.Custom;
      this.NumberOfTroopsKilledOnSide = 0;
      this.SiegeEngines = new SiegeEvent.SiegeEnginesContainer(BattleSideEnum.Defender, (SiegeEvent.SiegeEngineConstructionProgress) null);
      this._siegeEngineMissiles = new List<SiegeEvent.SiegeEngineMissile>();
      this.SiegeEngineMissiles = new MBReadOnlyList<SiegeEvent.SiegeEngineMissile>(this._siegeEngineMissiles);
      this.SetPrebuiltSiegeEngines();
      float height = 0.0f;
      Campaign.Current.MapSceneWrapper.GetHeightAtPoint(this.GatePosition, ref height);
      this.Party.Visuals.OnBesieged(new Vec3(this.GatePosition.x, this.GatePosition.y, height));
    }

    public void OnTroopsKilledOnSide(int killCount) => this.NumberOfTroopsKilledOnSide += killCount;

    public void AddSiegeEngineMissile(SiegeEvent.SiegeEngineMissile missile) => this._siegeEngineMissiles.Add(missile);

    public void RemoveDeprecatedMissiles() => this._siegeEngineMissiles.RemoveAll((Predicate<SiegeEvent.SiegeEngineMissile>) (missile => missile.CollisionTime.IsPast));

    private void SetPrebuiltSiegeEngines()
    {
      foreach (SiegeEngineType siegeEngine in Campaign.Current.Models.SiegeEventModel.GetPrebuiltSiegeEnginesOfSettlement(this))
      {
        float siegeEngineHitPoints = Campaign.Current.Models.SiegeEventModel.GetSiegeEngineHitPoints(this.SiegeEvent, siegeEngine, BattleSideEnum.Defender);
        SiegeEvent.SiegeEngineConstructionProgress constructionProgress = new SiegeEvent.SiegeEngineConstructionProgress(siegeEngine, 1f, siegeEngineHitPoints);
        this.SiegeEngines.AddPrebuiltEngineToReserve(constructionProgress);
        this.SiegeEvent.CreateSiegeObject(constructionProgress, this.SiegeEvent.GetSiegeEventSide(BattleSideEnum.Defender));
      }
    }

    public void GetAttackTarget(
      ISiegeEventSide siegeEventSide,
      SiegeEngineType siegeEngine,
      int siegeEngineSlot,
      out SiegeBombardTargets targetType,
      out int targetIndex)
    {
      targetType = SiegeBombardTargets.None;
      targetIndex = -1;
      int targetIndex1;
      float targetPriority;
      this.SiegeEvent.FindAttackableRangedEngineWithHighestPriority(siegeEventSide, siegeEngineSlot, out targetIndex1, out targetPriority);
      if (targetIndex1 == -1 || (double) MBRandom.RandomFloat * (double) targetPriority >= (double) targetPriority)
        return;
      targetIndex = targetIndex1;
      targetType = SiegeBombardTargets.RangedEngines;
    }

    public void FinalizeSiegeEvent()
    {
      this.ResetSiegeState();
      this.SiegeEvent = (SiegeEvent) null;
      this.Party.Visuals?.OnSiegeLifted();
      this.Party.Visuals?.RefreshLevelMask(this.Party);
      this.Party.Visuals?.SetMapIconAsDirty();
    }

    bool IMapEntity.IsMobileEntity => false;

    IMapEntity IMapEntity.AttachedEntity => (IMapEntity) null;

    IPartyVisual IMapEntity.PartyVisual => this.Party.Visuals;

    bool IMapEntity.ShowCircleAroundEntity => true;

    Vec2 IMapEntity.InteractionPosition => this.GatePosition;

    bool IMapEntity.OnMapClick(bool followModifierUsed)
    {
      if (!this.IsVisible)
        return false;
      MobileParty.MainParty.SetMoveGoToSettlement(this);
      return true;
    }

    void IMapEntity.OnOpenEncyclopedia() => Campaign.Current.EncyclopediaManager.GoToLink(this.EncyclopediaLink);

    bool IMapEntity.IsMainEntity() => false;

    void IMapEntity.OnHover() => InformationManager.AddTooltipInformation(typeof (Settlement), (object) this, (object) false);

    bool IMapEntity.IsEnemyOf(IFaction faction) => FactionManager.IsAtWarAgainstFaction(this.MapFaction, faction);

    bool IMapEntity.IsAllyOf(IFaction faction) => FactionManager.IsAlliedWithFaction(this.MapFaction, faction);

    public class SiegeLane
    {
      public Settlement.SiegeLaneEnum Id;
      
      public bool IsGate;
      
      public bool IsSiegeMachineApplicable;
      
      public bool IsBroken;

      public static void AutoGeneratedStaticCollectObjectsSiegeLane(
        object o,
        List<object> collectedObjects)
      {
        ((Settlement.SiegeLane) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
      }

      protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
      {
      }

      public static object AutoGeneratedGetMemberValueIsGate(object o) => (object) ((Settlement.SiegeLane) o).IsGate;

      public static object AutoGeneratedGetMemberValueIsSiegeMachineApplicable(object o) => (object) ((Settlement.SiegeLane) o).IsSiegeMachineApplicable;

      public static object AutoGeneratedGetMemberValueIsBroken(object o) => (object) ((Settlement.SiegeLane) o).IsBroken;

      public SiegeLane(Settlement.SiegeLaneEnum id, bool isGate, bool isSiegeMachineApplicable)
      {
        this.Id = id;
        this.IsGate = isGate;
        this.IsSiegeMachineApplicable = isSiegeMachineApplicable;
        this.IsBroken = false;
      }
    }

    public struct SettlementEventArguments
    {
      
      public Settlement TargetSettlement;

      public static void AutoGeneratedStaticCollectObjectsSettlementEventArguments(
        object o,
        List<object> collectedObjects)
      {
        ((Settlement.SettlementEventArguments) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
      }

      private void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects) => collectedObjects.Add((object) this.TargetSettlement);

      public static object AutoGeneratedGetMemberValueTargetSettlement(object o) => (object) ((Settlement.SettlementEventArguments) o).TargetSettlement;

      public SettlementEventArguments(Settlement targetSettlement) => this.TargetSettlement = targetSettlement;
    }

    public enum EventType
    {
      Undefined = -1, // 0xFFFFFFFF
      PlayerEntered = 0,
      PlayerLeft = 1,
    }

    public enum ManagementAIState
    {
      ConstructBuilding,
      MaximizeProduction,
      GiveQuest,
    }

    public enum SiegeLaneEnum
    {
      Left,
      Middle,
      Right,
    }

    public enum SiegeState
    {
      OnTheWalls,
      InTheLordsHall,
      Invalid,
    }
  }
}